### ISSUE TITLE
Integration tests for Decisioner with Hypothesis

### ISSUE THREAD

**Issue by cjmcgraw** [cjmcgraw/mooseyfate#9]

**Comment by cjmcgraw** [comment]
Add some trace to decisioner. Yo

**Comment by cjmcgraw** [comment]
Okay.

I will add print statements represent, at any given moment, what the decisioner has chosen as well as the competing fitness values

**Comment by cjmcgraw** [comment]
Added via f5744228223360cc77f87127e55540f119d254aa

**Comment by cjmcgraw** [comment]
So previously I was telling you about how we need to be careful with the first 100 as the fitness gets all whacky.

That we may want to extend the window, or alter it somehow

This is the problem with the chunky KNN I created if I put it with wimpy, brave and KNN:
1. Wimpy = 0.0, Brave = 0.0, KNN = 0.0
2. Wimpy = 1.0, Brave = 0.0, KNN = 1,9
99. Wimpy = 0.7, Brave = 0.3, KNN = 0.9
100. Wimpy = 0.7, Brave = 0.3, KNN = 0.9
101. Wimpy = 0.7, Brave = 0.7, KNN = 0.0

KNN resets at the window time because it assumes the previous KNN is finished.

This is a problem for us no matter what size we set the window at. If wimpy and KNN are competing and then KNN hits its window size (100 in this example) suddenly wimpy will be chosen forever and we are screwed.

The only solution I can come up with is to keep a rolling classification of fitness for current classification, and fitness for NEXT classification as well.

Then when we choose the next classification function we swap out our fitness in the abstract for the fitness we have been tracking for the NEXT (now chosen), and reset it for the new NEXT.

**Comment by cjmcgraw** [comment]
The above solution is actually relatively easy to implement, but it makes the code a bit more muddy.

However it is extremely effective at keeping a good rolling fitness for KNN and resolves previously problems about the window I described.

Because of this I will add unit tests to cover this specific situation

**Comment by cjmcgraw** [comment]
I added that to KNN via aa2e407f6f8e6f01eaf3fa4dae35095412baf286

It works relatively well now

**Comment by cjmcgraw** [comment]
Another concern is that the `WimpyHypothesis` is actually not doing its fitness correctly.

Instead its fitness is matching Brave's fitness.

I updated this via abf42a1f23cf789cd813244a9a5f57bc5b9fd5e3

**Comment by cjmcgraw** [comment]
So another KNN problem.

Integration tests prove that KNN cannot have a rolling window.

In theory this works, but in practice it does not: Let us imagine the following scenario:

color < 50 = aggressive
color > 50 = passive

We test against the first 100. We determine the metric with 99.9% certainty

The next one hundred we collect data on as well. However now we have an issue that was not previously considered.

Specifically the nature of those that are passive will be indeterminant in the system. So we will have to assume that everything < 50 is still aggressove, we have no way of knowing if we are correct.

Using the previous rolling window lets say that suddenly this shift occurs:

color > 50 = aggressive
color < 50 = passive

Now. we assume that everything < 50 was aggressive, so we never attack. Then we find that everything < 50 is now aggressive. So we mark them as aggressive eventually removing them from the data stream as well (over our window of 100).

So now our KNN gets the following algorithm:

color < 50 = aggressive
color > 50 = aggressive

KNN has now turned into wimpy.

This occurs any time any shift happens. We lose data from the previous aggressive monsters and gain new "aggressive" data. This new aggressive data repaints our guess-space, each iteration with new aggressive monsters turns KNN closer to wimpy

Because of this KNN must only have an initial training window and then ignore all time shifts from that point on

**Comment by cjmcgraw** [comment]
The final solution was to cut my losses and have two KNNs, one that works as expected over standard input and one chunky one that we most likely won't use without further consideration

**Comment by hasMichaels** [comment]
Thanks for adding integration tests for wimpy and brave; additionally, the integration environment you provided was easily extended.

I added DrPerceptron tests for:
- test_simpleResponse_WithDrPerceptron:
  - In this test we probe that it can train to be better than wimpy and worse than brave.
  - It is ASSERTED that DrPerceptron IS BETTER than Wimpy
  - It is ASSERTED that DrPerceptron IS WORSE than Brave
  - NO RATIO ASSERTIONS are made 
- test_frequencyResponse_WithDrPerceptron:
  - In this test we probe that it can train with staggered inputs 
  - it is ASSERTED that DrPerceptron is BETTER than Brave
  - it is IMPLICITLY ASSERTED that CONVERGENCE IN ~2xInput Window (10 iterations)
- test_frequencyResponse_forHarmonic_WithDrPerceptron
  - In this test we probe that Dr Perceptron can train with series data that is in harmonic with its input window size (5 inputs)
  - it is ASSERTED that DrPerceptron IS BETTER than BRAVE
  - it is ASSERTED that DrPerceptron's  WIN-RATIO is GREATER THAN 0.99

**Comment by hasMichaels** [comment]
One thing to note:  The current implementation of DrPerceptron is blind to attributes like color; instead, it's focus is currently reviewing historical information and based on them train on whether or not there are patters of aggression or non-aggression.

**Comment by hasMichaels** [comment]
Dr.P's Related Commits: https://github.com/cjmcgraw/mooseyfate/commit/d36371e56a23963c3f43e9370293fd1a0e5ce869
https://github.com/cjmcgraw/mooseyfate/commit/125c87573342bcbc3bcc22856945a6b758c5d64b

**Comment by hasMichaels** [comment]
Done
